### ISSUE TITLE
Still running error when setting eval_data!

### ISSUE THREAD

**Issue by lyhue1991** [DataCanvasIO/HyperGBM#82]
![image](https://user-images.githubusercontent.com/30676974/159284620-ce83214f-a87b-4a4a-be6d-bd36eaf547e4.png)

try eval_data like code below.
```python
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from hypergbm import make_experiment
X,y = datasets.load_breast_cancer(as_frame=True,return_X_y=True)
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,random_state=335)
dftrain = pd.concat([X_train,y_train],axis=1)
dfval = pd.concat([X_test,y_test],axis=1)


experiment = make_experiment(train_data=dftrain.copy(), 
                             target='target', 
                             reward_metric='precision',
                             eval_data=dfval.copy(),
                             max_trials=5)
estimator = experiment.run()
estimator
```

 it throws an error like this:

```
03-21 22:28:22 E hypernets.e._experiment.py 100 - ExperimentID:[HyperGBM_51f6515f9945cce8cf9365412d041ebe] - None: 'CompeteExperiment' object has no attribute 'y_eval_pred'
Traceback (most recent call last):
  File "/conda/envs/notebook/lib/python3.6/site-packages/hypernets/experiment/_experiment.py", line 86, in run
    callback.experiment_start(self)
  File "/conda/envs/notebook/lib/python3.6/site-packages/hypernets/experiment/_callback.py", line 577, in experiment_start
    d = ExperimentExtractor(exp).extract()
  File "/conda/envs/notebook/lib/python3.6/site-packages/hypernets/experiment/_extractor.py", line 668, in extract
    if self.is_evaluated():
  File "/conda/envs/notebook/lib/python3.6/site-packages/hypernets/experiment/_extractor.py", line 654, in is_evaluated
    return self.exp.X_eval is not None and self.exp.y_eval is not None and self.exp.y_eval_pred is not None
AttributeError: 'CompeteExperiment' object has no attribute 'y_eval_pred'
```
Could this bug be fixed in the next version?

**Comment by oaksharks** [comment]
Thanks for your report, it has been fixed, you can refer to this issue:  https://github.com/DataCanvasIO/HyperGBM/issues/80

**Comment by lyhue1991** [comment]
I update the code of hypernets. And I  set cv=False to let the eval_data be used. It  raises an other error.

code like below

```Python
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from hypergbm import make_experiment
X,y = datasets.load_breast_cancer(as_frame=True,return_X_y=True)
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,random_state=335)
dftrain = pd.concat([X_train,y_train],axis=1)
dfval = pd.concat([X_test,y_test],axis=1)


experiment = make_experiment(train_data=dftrain.copy(), 
                             target='target', 
                             reward_metric='precision',
                             eval_data=dfval.copy(),
                             cv=False,
                             max_trials=5)
estimator = experiment.run()
estimator

```

The error is raised at the ensemble stage!

```
03-23 06:59:05 E hypernets.e._experiment.py 100 - ExperimentID:[HyperGBM_51f6515f9945cce8cf9365412d041ebe] - None: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/hadoop-poimining/.local/lib/python3.6/site-packages/hypernets/experiment/_experiment.py", line 89, in run
    y_eval=self.y_eval, **kwargs)
  File "/home/hadoop-poimining/.local/lib/python3.6/site-packages/hypernets/experiment/compete.py", line 1551, in train
    raise e
  File "/home/hadoop-poimining/.local/lib/python3.6/site-packages/hypernets/experiment/compete.py", line 1546, in train
    self.step_end(output=step.get_fitted_params())
  File "/home/hadoop-poimining/.local/lib/python3.6/site-packages/hypernets/experiment/_experiment.py", line 119, in step_end
    callback.step_end(self, self.current_step, output, elapsed)
  File "/home/hadoop-poimining/.local/lib/python3.6/site-packages/hypernets/experiment/_callback.py", line 573, in step_end
    step_meta_dict = ExperimentExtractor.extract_step(step_index, step).to_dict()
  File "/home/hadoop-poimining/.local/lib/python3.6/site-packages/hypernets/experiment/_extractor.py", line 632, in extract_step
    extension = extractor.get_extension()
  File "/home/hadoop-poimining/.local/lib/python3.6/site-packages/hypernets/experiment/_extractor.py", line 208, in get_extension
    ret_extension = self._get_extension()
  File "/home/hadoop-poimining/.local/lib/python3.6/site-packages/hypernets/experiment/_extractor.py", line 530, in _get_extension
    'models': [get_tree_importances(m) for m in get_models(estimator)]
TypeError: 'NoneType' object is not iterable
```

**Comment by oaksharks** [comment]
Thanks for your feedback, did you got this error in the jupyter notebook? and the error page like:
![image](https://user-images.githubusercontent.com/7763696/159616197-630723f9-2dad-4d5f-b78d-9a8ff6696b80.png)

The reason for this error may be that set `cv=False` will result in getting `None` of models:
```python
        def get_models(estimator_):
            if hasattr(estimator_, 'cv_gbm_models_'):  
                return estimator_.cv_gbm_models_  # maybe return None here
            if hasattr(estimator_, 'cv_models_'):  
                return estimator_.cv_models_ # maybe return None here too
            return []

        estimators = []
        for i, estimator in enumerate(ensemble.estimators):
            if estimator is not None:
                _e_mate = {
                    'index': i,
                    'weight': ensemble.weights_[i],
                    'lift': ensemble.scores_[i],
                    'models': [get_tree_importances(m) for m in get_models(estimator)]  # report error here
                }
                estimators.append(_e_mate)
        return {'estimators': estimators}
```

If so, I suggest you set `cv=True` or uninstall `hbboard-widget` by the following command until I fixed this error：
````
# disable experiment visualization implement by hboard  
pip uninstall hboard-widget 
````

Ref：
https://github.com/DataCanvasIO/Hypernets/blob/71cd6e77d6ef802f5e7721553ddf589d06dd5737/hypernets/experiment/_extractor.py#L516-L521

**Comment by oaksharks** [comment]
Hi @lyhue1991 , the bug was fixed now, you can update [Hypernets](https://github.com/DataCanvasIO/Hypernets) and try again.

**Comment by lyhue1991** [comment]
@oaksharks  Thanks, it works okay now.  
A small suggestion in the API design.

when the eval_data is setted,  can the cross-validation automatically disabled (cv = False)?.

like below. 

```python
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from hypergbm import make_experiment
X,y = datasets.load_breast_cancer(as_frame=True,return_X_y=True)
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,random_state=335)
dftrain = pd.concat([X_train,y_train],axis=1)
dfval = pd.concat([X_test,y_test],axis=1)

experiment = make_experiment(train_data=dftrain.copy(), 
                             target='target', 
                             reward_metric='precision',
                             eval_data=dfval.copy(),
                             cv=False,  # can this line be omitted?
                             max_trials=5)
estimator = experiment.run()
estimator

```

**Comment by oaksharks** [comment]
Thanks for your suggestion, I think it will help us to improve hypergbm.
