### ISSUE TITLE
some error in distributed training

### ISSUE THREAD

**Issue by simm13** [DataCanvasIO/HyperGBM#84]
**when i start with the distributed training example:**
    def train():
       cluster = LocalCluster(processes=False)
       client = Client(cluster)
       train_data = dd.from_pandas(dsutils.load_blood(), npartitions=1)
       experiment = make_experiment(train_data, target='Class')
       estimator = experiment.run()
      print(estimator)
**some error occured:**
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 5, in train
  File "/root/anaconda3/lib/python3.9/site-packages/hypergbm/experiment.py", line 104, in make_experiment
    tb = get_tool_box(train_data)
  File "/root/anaconda3/lib/python3.9/site-packages/hypernets/tabular/_base.py", line 68, in get_tool_box
    raise ValueError(f'No toolbox found for your data with types: {[type(x) for x in data]}. '
ValueError: No toolbox found for your data with types: [<class 'dask.dataframe.core.DataFrame'>]. Registered tabular toolboxes are ['ToolBox'].

**how can i sovle it?**

**Comment by lixfz** [comment]
How did you install HyperGBM?

List your installed python packages here, pls.
