### ISSUE TITLE
运行简单示例程序报错

### ISSUE THREAD

**Issue by apooth** [DataCanvasIO/HyperGBM#85]
您好，我新建了一个虚拟环境专门安装HyperGBM，依赖包都已成功安装，但是运行最简单的示例程序报错了，可否帮忙看一下是哪里出了问题？谢谢！
运用以下示例程序：
from hypergbm import make_experiment
from hypernets.tabular.datasets import dsutils

train_data = dsutils.load_blood()
experiment = make_experiment(train_data, target='Class')
estimator = experiment.run()
print(estimator)

报错内容很长，截取最前面几条：
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Software\Anaconda3\envs\hp\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Software\Anaconda3\envs\hp\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Software\Anaconda3\envs\hp\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Software\Anaconda3\envs\hp\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,

还包括多个MemoryError例如：
    import scipy.linalg._interpolative_backend as _backend
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 934, in get_code
  File "<frozen importlib._bootstrap_external>", line 1033, in get_data
MemoryError

**Comment by lixfz** [comment]
谢谢您的反馈！

为进一步诊断，烦请提供更多信息：
1. 您的虚拟机的配置情况：cpu核数、mem大小、Windows版本
2. 您安装HyperGBM的方式（ 包括您创建conda环境的步骤）
3. 完整的log，可以以附件的形式传上来

**Comment by apooth** [comment]
您好，运行示例程序几秒后，CPU占用接近100%。

1. CPU：8核，内存16G，C盘可用14G，D盘可用65G，Win10，Python3.9（3.7、3.8、3.9都试过不行）
2. pip install hypergbm

打印的日志已上传
[hypergbm.pdf](https://github.com/DataCanvasIO/HyperGBM/files/8875369/hypergbm.pdf)
)

**Comment by lixfz** [comment]
您上传的log中有如下信息：

![image](https://user-images.githubusercontent.com/68989761/173173571-2932e00e-b508-4db5-9954-7303a999aa53.png)

请检查您的环境中xgboost是否正确安装，建议使用64位的python环境。

**Comment by lixfz** [comment]
另外，由于windows中python多进程调度存在一些局限性，建议将您的测试代码调整如下：

```python
from hypergbm import make_experiment
from hypernets.tabular.datasets import dsutils


def train():
    train_data = dsutils.load_blood()
    experiment = make_experiment(train_data, target='Class')
    estimator = experiment.run()
    print(estimator)


if __name__ == '__main__':
    train()

```

**Comment by apooth** [comment]
您好，感谢您的解答。我增加了虚拟内存，系统报错：
![1](https://user-images.githubusercontent.com/107103220/173178105-2e2aa2b5-dfff-4693-befa-72836935c6fb.png)
后续把程序放进if __name__ == '__main__':里，运行成功了，感谢！
另外Woodwork和Featuretools后续可能不支持Python3.7，报错了一些Future Warning：
![2](https://user-images.githubusercontent.com/107103220/173180119-61f6375c-a1b9-4b79-94a5-512d0eaf6413.png)

**Comment by lixfz** [comment]
恭喜运行成功！

关于FeatureTools，我们已经做了适配，目前HyperGBM支持FeatureTools v0.23及以上版本。
对于Python3.7，如果想屏蔽您所看到的警告信息，可以将FeatureTools 降级到较低的版本，比如v0.27.1。

**Comment by lixfz** [comment]
补充：如果您在使用HyperGBM的过程中修改了个别依赖库的版本的话，建议清空系统临时目录下的子目录`workdir`然后再重新运行HyperGBM

**Comment by apooth** [comment]
按照您的提示，成功消除了警告，目前正常运行，十分感谢！
