### ISSUE TITLE
hypergbm fiting bug

### ISSUE THREAD

**Issue by wangjianqiao111** [DataCanvasIO/HyperGBM#99]
<em>Please make sure that this is a bug. </em>

**System information**
- OS Platform and Distribution (e.g., CentOS 7.6):linux
- Python version:3.7
- HyperGBM version:0.2.2, 0.2.5
- Other Python packages(run `pip list`):

**Describe the current behavior**

2023-03-01 17:32:55.332 [ERROR] 03-01 17:32:55 E hypernets.m.hyper_model.py 71 - run_trail failed! trail_no=5
2023-03-01 17:32:55.333 [ERROR] 03-01 17:32:55 E hypernets.m.hyper_model.py 73 - Traceback (most recent call last):
2023-03-01 17:32:55.333 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hypernets/model/hyper_model.py", line 64, in _run_trial
2023-03-01 17:32:55.333 [ERROR]     **fit_kwargs)
2023-03-01 17:32:55.333 [ERROR] ValueError: not enough values to unpack (expected 3, got 2)

**Describe the expected behavior**

Training completed

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Jupyter notebook.

from hypergbm import make_experiment
experiment = make_experiment(train_data, target='y', reward_metric='auc', cv=True)
estimator = experiment.run()

**Are you willing to submit PR?(Yes/No)**

Yes

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. 
If including tracebacks, please include the full traceback. Large logs and files 
should be attached.

**Comment by lixfz** [comment]
Can you upload a piece of train_data so that we reproduce this issue

**Comment by wangjianqiao111** [comment]
[Uploading y_yes (1).zip…]()

**Comment by wangjianqiao111** [comment]
[y_yes (1).zip](https://github.com/DataCanvasIO/HyperGBM/files/10904867/y_yes.1.zip)

**Comment by wangjianqiao111** [comment]
![Uploading 截屏2023-03-07 上午10.40.06.png…]()

**Comment by wangjianqiao111** [comment]
Please take a look as soon as possible，thank you

**Comment by wangjianqiao111** [comment]
03-07 10:47:29 E hypernets.m.hyper_model.py 71 - run_trail failed! trail_no=8
03-07 10:47:29 E hypernets.m.hyper_model.py 73 - Traceback (most recent call last):
  File "/Users/wjq/PycharmProjects/pythonProject1venv/venv/lib/python3.7/site-packages/hypernets/model/hyper_model.py", line 64, in _run_trial
    **fit_kwargs)
  File "/Users/wjq/PycharmProjects/pythonProject1venv/venv/lib/python3.7/site-packages/hypergbm/hyper_gbm.py", line 306, in fit_cross_validation
    fold_est.fit(x_train_fold, y_train_fold, **fit_kwargs)
  File "/Users/wjq/PycharmProjects/pythonProject1venv/venv/lib/python3.7/site-packages/hypergbm/estimators.py", line 465, in fit
    kwargs = self.prepare_fit_kwargs(X, y, kwargs)
  File "/Users/wjq/PycharmProjects/pythonProject1venv/venv/lib/python3.7/site-packages/hypergbm/estimators.py", line 449, in prepare_fit_kwargs
    self.feature_names_in_ = X.columns.tolist()
AttributeError: can't set attribute

**Comment by lixfz** [comment]
> 03-07 10:47:29 E hypernets.m.hyper_model.py 71 - run_trail failed! trail_no=8
> 03-07 10:47:29 E hypernets.m.hyper_model.py 73 - Traceback (most recent call last):
> File "/Users/wjq/PycharmProjects/pythonProject1venv/venv/lib/python3.7/site-packages/hypernets/model/hyper_model.py", line 64, in run_trial
> **fit_kwargs)
> File "/Users/wjq/PycharmProjects/pythonProject1venv/venv/lib/python3.7/site-packages/hypergbm/hyper_gbm.py", line 306, in fit_cross_validation
> fold_est.fit(x_train_fold, y_train_fold, **fit_kwargs)
> File "/Users/wjq/PycharmProjects/pythonProject1venv/venv/lib/python3.7/site-packages/hypergbm/estimators.py", line 465, in fit
> kwargs = self.prepare_fit_kwargs(X, y, kwargs)
> File "/Users/wjq/PycharmProjects/pythonProject1venv/venv/lib/python3.7/site-packages/hypergbm/estimators.py", line 449, in prepare_fit_kwargs
> self.feature_names_in = X.columns.tolist()
> AttributeError: can't set attribute

It's a another new  issue?
you  can downgrade xgboost version to `"<1.6.0"`  or upgrade hypergbm  to latest.

**Comment by lixfz** [comment]
Can you upload a piece of train_data so that we reproduce the original issue?

**Comment by wangjianqiao111** [comment]
upgrade hypergbm to latest ? Now my hypergbm=='0.2.5',it is latest, and xgboost==1.6.2,but i still get the error

**Comment by wangjianqiao111** [comment]
train_data is that i just upload the data,i get original issue is on APS,but on my local computer pycharm ,i get the second error,I doubt that these two problems are actually one

**Comment by wangjianqiao111** [comment]
Thank you very much ,The above two problems have been solved, but I have encountered a new problem:

the code:

from hypergbm import make_experimen
experiment = make_experiment(g, target='y', reward_metric='recall', cv=True)
experiment.run()

error:

2023-03-07 19:22:10.138 [ERROR] 03-07 19:22:10 E hypernets.m.hyper_model.py 71 - run_trail failed! trail_no=1
2023-03-07 19:22:10.157 [ERROR] 03-07 19:22:10 E hypernets.m.hyper_model.py 73 - Traceback (most recent call last):
2023-03-07 19:22:10.157 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hypernets/model/hyper_model.py", line 64, in _run_trial
2023-03-07 19:22:10.157 [ERROR]     **fit_kwargs)
2023-03-07 19:22:10.157 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hypergbm/hyper_gbm.py", line 320, in fit_cross_validation
2023-03-07 19:22:10.157 [ERROR]     fold_scores = self.get_scores(y_val_fold, proba, metrics)
2023-03-07 19:22:10.157 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hypergbm/hyper_gbm.py", line 354, in get_scores
2023-03-07 19:22:10.157 [ERROR]     classes=self.classes_, pos_label=self.pos_label)
2023-03-07 19:22:10.157 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hypernets/tabular/metrics.py", line 65, in calc_score
2023-03-07 19:22:10.157 [ERROR]     score[metric] = sk_metrics.recall_score(y_true, y_preds, **recall_options)
2023-03-07 19:22:10.157 [ERROR]   File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
2023-03-07 19:22:10.157 [ERROR]     return f(**kwargs)
2023-03-07 19:22:10.157 [ERROR]   File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1741, in recall_score
2023-03-07 19:22:10.157 [ERROR]     zero_division=zero_division)
2023-03-07 19:22:10.157 [ERROR]   File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
2023-03-07 19:22:10.157 [ERROR]     return f(**kwargs)
2023-03-07 19:22:10.157 [ERROR]   File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1434, in precision_recall_fscore_support
2023-03-07 19:22:10.158 [ERROR]     pos_label)
2023-03-07 19:22:10.158 [ERROR]   File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1257, in _check_set_wise_labels
2023-03-07 19:22:10.158 [ERROR]     "%r" % (pos_label, present_labels))
2023-03-07 19:22:10.158 [ERROR] ValueError: pos_label=1 is not a valid label: array(['no', 'yes'], dtype='<U3')

**Comment by lixfz** [comment]
For binary task, `pos_label` (default=1) is required to evaluate model with recall or f1,  see [sklearn.metrics.recall_score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.recall_score.html) for more details.

In hypergbm, the option 'pos_label` is also supported:

```python
experiment = make_experiment(train_data, target='y', reward_metric='recall', cv=True, pos_label='yes')
estimator = experiment.run()
```
